ALTER TABLE "FoodOrder" ALTER COLUMN "breakfast" SET DEFAULT false;
ALTER TABLE "FoodOrder" ALTER COLUMN "lunch" SET DEFAULT false;
ALTER TABLE "FoodOrder" ALTER COLUMN "dinner" SET DEFAULT false;
ALTER TABLE "FoodOrder" ADD COLUMN "tea" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "FoodOrder" ADD COLUMN "cutFruits" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "FoodOrder" ADD COLUMN "gymDiet" BOOLEAN NOT NULL DEFAULT false;
